// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-leads.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-leads.ts
var list_leads_default = defineTool({
  name: "list_leads",
  title: "List leads",
  description: "List brokerage leads who submitted the AI readiness scorecard, newest first, with their assessment score and band.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max leads to return (default 20)."),
    band: z.string().optional().describe("Filter by readiness band, e.g. 'Emerging'."),
    search: z.string().optional().describe("Case-insensitive match on email or brokerage name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, band, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("leads").select(
      "id, first_name, last_name, email, brokerage_name, agent_count, top_priority, created_at, assessments(total_score, band)"
    ).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (search) {
      query = query.or(`email.ilike.%${search}%,brokerage_name.ilike.%${search}%`);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).filter(
      (row) => !band || (row.assessments ?? []).some((a) => a.band === band)
    );
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, leads: rows }
    };
  }
});

// src/lib/mcp/tools/get-lead-assessment.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_lead_assessment_default = defineTool2({
  name: "get_lead_assessment",
  title: "Get lead assessment",
  description: "Get one lead's full AI readiness assessment: contact details, per-question answers, category scores, band and recommendations.",
  inputSchema: {
    lead_id: z2.string().uuid().describe("The lead's UUID, as returned by list_leads.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("leads").select("*, assessments(*)").eq("id", lead_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No lead found with id ${lead_id}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/assessment-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var CATEGORY_COLUMNS = {
  "Data Readiness": "category_data_readiness",
  "Workflow Execution": "category_workflow_execution",
  Governance: "category_governance",
  "Adoption & ROI": "category_adoption_roi"
};
function average(values) {
  if (!values.length) return null;
  return Math.round(values.reduce((s, v) => s + v, 0) / values.length * 100) / 100;
}
var assessment_summary_default = defineTool3({
  name: "assessment_summary",
  title: "Assessment summary",
  description: "Aggregate statistics across all AI readiness assessments: total count, average score, band distribution and average score per category.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("assessments").select(
      "total_score, band, category_data_readiness, category_workflow_execution, category_governance, category_adoption_roi"
    );
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const bands = {};
    for (const row of rows) {
      const band = row.band ?? "Unknown";
      bands[band] = (bands[band] ?? 0) + 1;
    }
    const categories = Object.fromEntries(
      Object.entries(CATEGORY_COLUMNS).map(([label, column]) => [
        label,
        average(rows.map((r) => r[column]).filter((v) => typeof v === "number"))
      ])
    );
    const summary = {
      total_assessments: rows.length,
      average_total_score: average(
        rows.map((r) => r.total_score).filter((v) => typeof v === "number")
      ),
      band_distribution: bands,
      average_category_scores: categories
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "znrahrqrariflnxfwhvh";
var mcp_default = defineMcp({
  name: "ai-brokerage-accelerator",
  title: "AI Brokerage Accelerator",
  version: "0.1.0",
  instructions: "Tools for the AI Brokerage Accelerator readiness scorecard. Use `list_leads` to browse submitted leads, `get_lead_assessment` for one lead's full answers and recommendations, and `assessment_summary` for aggregate benchmarks. Access is scoped to the signed-in user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, get_lead_assessment_default, assessment_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
